#ficheiros usados no projeto
files = ../src/structs.c ../src/fileUtils.c ../src/parsing.c ../src/readWrite.c ../src/main.c

compile_g1: #compilar o guião 1
	gcc $(files) -o guiao-1 -lm

run_g1_e1: #correr o exercício 1 do guião 1
	./guiao-1 exercicio-1

run_g1_e2:
	./guiao-1 exercicio-2

run_all:
	./guiao-1 all

clean:
	rm guiao-1
