all: querie1 querie2 querie3 querie4 querie5 querie6 querie7 querie8 querie9
	rm -r __pycache__

querie1:
	python3 querie1.py

querie2:
	python3 querie2.py

querie3:
	python3 querie3.py

querie4:
	python3 querie4.py

querie5:
	python3 querie5.py 100 2000-01-01 2022-01-30 q5_exp_res_1
	python3 querie5.py 10000 2000-01-01 2022-01-30 q5_exp_res_2

querie6:
	python3 querie6.py 100 JavaScript q6_exp_res_1
	python3 querie6.py 10000 Java q6_exp_res_2

querie7:
	python3 querie7.py 2015-06-05 q7_exp_res_1
	python3 querie7.py 2017-11-03 q7_exp_res_2

querie8:
	python3 querie8.py 30 2015-01-01 q8_exp_res_1
	python3 querie8.py 500 2016-01-01 q8_exp_res_2

querie9:
	python3 querie9.py 100 q9_exp_res_1
	python3 querie9.py 10000 q9_exp_res_2