all: querie1 querie2 querie3 querie4 querie5 querie6 querie7 querie8 querie9
	rm -r __pycache__

querie1:
	python3 querie1.py

querie2:
	python3 querie2.py

querie3:
	python3 querie3.py

querie4:
	python3 querie4.py

querie5:
	python3 querie5.py 150 2000-01-01 2022-01-30

querie6:
	python3 querie6.py 50 JavaScript

querie7:
	python3 querie7.py 2015-06-05

querie8:
	python3 querie8.py 30 2015-01-01

querie9:
	python3 querie9.py 30